# Generated by Django 6.0.6 on 2026-06-19 09:43

import django.db.models.deletion
import mockserver.models.endpoint
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Unique code for the collection, example path: <BASE_URL>/mockapi/{code}/{endpoint-path}', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', help_text='Public collections are visible to all users, while private collections are only visible to the creator and shared users.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SharedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('EDITOR', 'Editor')], default='VIEWER', max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_collections', to='mockserver.collection')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.CharField(help_text='Unique path for the endpoint, example path: <BASE_URL>/mockapi/{code}/{path}', max_length=200)),
                ('allowed_methods', models.JSONField(default=mockserver.models.endpoint._default_allowed_methods)),
                ('http_status_code', models.IntegerField(default=200)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('delay_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='mockserver.collection')),
            ],
            options={
                'unique_together': {('collection', 'path')},
            },
        ),
    ]
