# Generated by Django 6.0.6 on 2026-06-24 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mockserver", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sharedcollection",
            unique_together={("collection", "shared_with")},
        ),
    ]
